[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[project]
name = "basic_ml"
version = "0.0.1"

[tool.setuptools.packages]
find = {}

[tool.isort]
profile = "black"
